#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true

#App
app.version=1.0.0
android.version=1.0.0
android.versionCode=1
ios.buildNumber=1

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
